#############
# RESOURCES #
#############
resources:
- name: gpos_github_release
  type: github-release
  source:
    user: greenplum-db
    repository: gpos
    access_token: {{gposbot_access_token}}
- name: orca_github_release
  type: github-release
  source:
    user: greenplum-db
    repository: gporca
    access_token: {{gporcabot_access_token}}
- name: gpos_src
  type: git
  source:
    branch: 129649319_shared
    private_key: {{gpos_deploy_key}}
    uri: git@github.com:xinzweb/gpos.git
- name: xerces_patch
  type: git
  source:
    branch: master
    paths:
    - patches/xerces-c-gpdb.patch
    - concourse/xerces-c
    - concourse/package_tarball.bash
    private_key: {{gporca_deploy_key}}
    uri: git@github.com:greenplum-db/gporca.git
- name: orca_src
  type: git
  source:
    branch: 129649319_shared
    private_key: {{gporca_deploy_key}}
    uri: git@github.com:xinzweb/gporca.git
- name: bin_xerces_centos5
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_xerces_centos5.tar.gz
- name: bin_xerces_osx32
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_xerces_osx32.tar.gz
- name: bin_gpos_centos5_debug
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_centos5_debug.tar.gz

- name: bin_gpos_osx32_debug
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_osx32_debug.tar.gz

- name: bin_gpos_osx32_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_osx32_release.tar.gz

- name: bin_gpos_centos5_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_gpos_centos5_release.tar.gz
- name: bin_orca_centos5_debug
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_centos5_debug.tar.gz
- name: bin_orca_centos5_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_centos5_release.tar.gz
- name: bin_orca_osx32_debug
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_osx32_debug.tar.gz
- name: bin_orca_osx32_release
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: bin_orca_osx32_release.tar.gz
- name: regression_diffs
  type: s3
  source:
     access_key_id: {{aws-access-key-id}}
     bucket: {{bucket-name}}
     region_name: {{aws-region}}
     secret_access_key: {{aws-secret-access-key}}
     versioned_file: regression.diffs
- name: regression_out
  type: s3
  source:
     access_key_id: {{aws-access-key-id}}
     bucket: {{bucket-name}}
     region_name: {{aws-region}}
     secret_access_key: {{aws-secret-access-key}}
     versioned_file: regression.out

########
# JOBS #
########
jobs:
- name: gpos_publish_tag
  max_in_flight: 1
  plan:
  - aggregate:
    - get: gpos_src
      passed:
      - gpos_centos5_release
      - gpos_centos5_debug
#      - gpos_osx32_release
#      - gpos_osx32_debug
      trigger: true
    - get: bin_gpos_centos5_release
      passed:
      - gpos_centos5_release
    - get: bin_gpos_centos5_debug
      passed:
      - gpos_centos5_debug
#    - get: bin_gpos_osx32_release
#      passed:
#      - gpos_osx32_release
#    - get: bin_gpos_osx32_debug
#      passed:
#      - gpos_osx32_debug
  - task: gpos_publish_tag
    file: gpos_src/concourse/publish_tag.yml
  - put: gpos_github_release
    params:
      name: gpos_github_release_stage/tag.txt
      tag: gpos_github_release_stage/tag.txt
      commitish: gpos_github_release_stage/commit.txt
      globs:
        - gpos_github_release_stage/bin_gpos_centos5_release.tar.gz
        - gpos_github_release_stage/bin_gpos_centos5_debug.tar.gz
#        - gpos_github_release_stage/bin_gpos_osx32_release.tar.gz
#        - gpos_github_release_stage/bin_gpos_osx32_debug.tar.gz

- name: orca_publish_tag
  max_in_flight: 1
  plan:
  - aggregate:
    - get: orca_src
      passed:
      - orca_centos5_release
      - orca_centos5_debug
#      - orca_osx32_release
#      - orca_osx32_debug
      trigger: true
    - get: bin_orca_centos5_release
      passed:
      - orca_centos5_release
    - get: bin_orca_centos5_debug
      passed:
      - orca_centos5_debug
#    - get: bin_orca_osx32_release
#      passed:
#      - orca_osx32_release
#    - get: bin_orca_osx32_debug
#      passed:
#      - orca_osx32_debug
  - task: orca_publish_tag
    file: orca_src/concourse/publish_tag.yml
  - put: orca_github_release
    params:
      name: orca_github_release_stage/tag.txt
      tag: orca_github_release_stage/tag.txt
      commitish: orca_github_release_stage/commit.txt
      globs:
        - orca_github_release_stage/bin_orca_centos5_release.tar.gz
        - orca_github_release_stage/bin_orca_centos5_debug.tar.gz
#        - orca_github_release_stage/bin_orca_osx32_release.tar.gz
#        - orca_github_release_stage/bin_orca_osx32_debug.tar.gz

- name: xerces_centos5
  max_in_flight: 2
  plan:
  - get: xerces_patch
    trigger: true
  - aggregate:
    - task: build
      file: xerces_patch/concourse/xerces-c/build_xerces_centos5.yml
  - aggregate:
    - task: package_tarball
      file: xerces_patch/concourse/xerces-c/package_tarball_centos5.yml
  - aggregate:
    - put: bin_xerces_centos5
      params:
        from: package_tarball_centos5/bin_xerces_centos5.tar.gz

#- name: xerces_osx32
#  plan:
#    - get: xerces_patch
#      trigger: true
#    - task: build
#      file: xerces_patch/concourse/xerces-c/build_xerces_osx32.yml
#    - task: package_tarball
#      file: xerces_patch/concourse/xerces-c/package_tarball_osx32.yml
#    - put: bin_xerces_osx32
#      params:
#        from: package_tarball_osx32/bin_xerces_osx32.tar.gz

- name: gpos_centos5_release
  max_in_flight: 2
  plan:
  - get: gpos_src
    trigger: true
  - task: build_and_test_release
    file: gpos_src/concourse/build_centos5_release.yml
  - task: package_tarball_release
    file: gpos_src/concourse/package_tarball_centos5_release.yml
  - put: bin_gpos_centos5_release
    params:
      from: package_tarball_release/bin_gpos_centos5_release.tar.gz

- name: gpos_centos5_debug
  max_in_flight: 2
  plan:
  - get: gpos_src
    trigger: true
  - task: build_and_test_debug
    file: gpos_src/concourse/build_centos5_debug.yml
  - task: package_tarball_debug
    file: gpos_src/concourse/package_tarball_centos5_debug.yml
  - put: bin_gpos_centos5_debug
    params:
      from: package_tarball_debug/bin_gpos_centos5_debug.tar.gz

#- name: gpos_osx32_release
#  plan:
#  - get: gpos_src
#    trigger: true
#  - task: build_and_test_release
#    file: gpos_src/concourse/build_osx32_release.yml
#  - task: package_tarball_release
#    file: gpos_src/concourse/package_tarball_osx32_release.yml
#  - put: bin_gpos_osx32_release
#    params:
#      from: package_tarball_osx32_release/bin_gpos_osx32_release.tar.gz

#- name: gpos_osx32_debug
#  plan:
#  - get: gpos_src
#    trigger: true
#  - task: build_and_test_debug
#    file: gpos_src/concourse/build_osx32_debug.yml
#  - task: package_tarball_debug
#    file: gpos_src/concourse/package_tarball_osx32_debug.yml
#  - put: bin_gpos_osx32_debug
#    params:
#      from: package_tarball_osx32_debug/bin_gpos_osx32_debug.tar.gz

- name: orca_centos5_release
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_gpos_centos5_release
    passed:
    - gpos_publish_tag
  - get: bin_xerces_centos5
    passed:
    - xerces_centos5
  - task: build_and_test_release
    file: orca_src/concourse/build_and_test_centos5_release.yml
  - task: package_tarball_release
    file: orca_src/concourse/package_tarball_centos5_release.yml
  - put: bin_orca_centos5_release
    params:
      from: package_tarball_release/bin_orca_centos5_release.tar.gz

- name: orca_centos5_debug
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_gpos_centos5_debug
    passed:
    - gpos_publish_tag
  - get: bin_xerces_centos5
    passed:
    - xerces_centos5
  - task: build_and_test_debug
    file: orca_src/concourse/build_and_test_centos5_debug.yml
  - task: package_tarball_debug
    file: orca_src/concourse/package_tarball_centos5_debug.yml
  - put: bin_orca_centos5_debug
    params:
      from: package_tarball_debug/bin_orca_centos5_debug.tar.gz

#- name: orca_osx32_release
#  serial_groups:
#    - osx
#  plan:
#  - get: orca_src
#    trigger: true
#  - get: bin_gpos_osx32_release
#    passed:
#    - gpos_publish_tag
#  - get: bin_xerces_osx32
#    passed:
#    - xerces_osx32
#  - task: build_and_test_release
#    file: orca_src/concourse/build_and_test_osx32_release.yml
#  - task: package_tarball_release
#    file: orca_src/concourse/package_tarball_osx32_release.yml
#  - put: bin_orca_osx32_release
#    params:
#      from: package_tarball_osx32_release/bin_orca_osx32_release.tar.gz

#- name: orca_osx32_debug
#  serial_groups:
#    - osx
#  plan:
#  - get: orca_src
#    trigger: true
#  - get: bin_gpos_osx32_debug
#    passed:
#    - gpos_publish_tag
#  - get: bin_xerces_osx32
#    passed:
#    - xerces_osx32
#  - task: build_and_test_debug
#    file: orca_src/concourse/build_and_test_osx32_debug.yml
#  - task: package_tarball_debug
#    file: orca_src/concourse/package_tarball_osx32_debug.yml
#  - put: bin_orca_osx32_debug
#    params:
#      from: package_tarball_osx32_debug/bin_orca_osx32_debug.tar.gz
